In [2]:
import pandas as pd

# Adjust the delimiter based on your file's structure
df = pd.read_csv('./Resources/bgg_dataset.csv', delimiter=';')

# Display the first few rows
print(df.head())

         ID                               Name  Year Published  Min Players  \
0  174430.0                         Gloomhaven          2017.0            1
1  161936.0          Pandemic Legacy: Season 1          2015.0            2
2  224517.0                  Brass: Birmingham          2018.0            2
3  167791.0                  Terraforming Mars          2016.0            1
4  233078.0  Twilight Imperium: Fourth Edition          2017.0            3

   Max Players  Play Time  Min Age  Users Rated Rating Average  BGG Rank  \
0            4        120       14        42055           8,79         1
1            4         60       13        41643           8,61         2
2            4        120       14        19217           8,66         3
3            5        120       12        64864           8,43         4
4            6        480       14        13468           8,70         5

  Complexity Average  Owned Users  \
0               3,86      68323.0
1               2,84      65294.0
2               3,91      28785.0
3               3,24      87099.0
4               4,22      16831.0

                                           Mechanics  \
0  Action Queue, Action Retrieval, Campaign / Bat...
1  Action Points, Cooperative Game, Hand Manageme...
2  Hand Management, Income, Loans, Market, Networ...
3  Card Drafting, Drafting, End Game Bonuses, Han...
4  Action Drafting, Area Majority / Influence, Ar...

                          Domains
0  Strategy Games, Thematic Games
1  Strategy Games, Thematic Games
2                  Strategy Games
3                  Strategy Games
4  Strategy Games, Thematic Games

In [3]:
# Fill NaN values in the 'ID' column with 0
df['ID'] = df['ID'].fillna(0).astype(int)

# Display the first few rows of the DataFrame to check the result
print(df.head())

       ID                               Name  Year Published  Min Players  \
0  174430                         Gloomhaven          2017.0            1
1  161936          Pandemic Legacy: Season 1          2015.0            2
2  224517                  Brass: Birmingham          2018.0            2
3  167791                  Terraforming Mars          2016.0            1
4  233078  Twilight Imperium: Fourth Edition          2017.0            3

   Max Players  Play Time  Min Age  Users Rated Rating Average  BGG Rank  \
0            4        120       14        42055           8,79         1
1            4         60       13        41643           8,61         2
2            4        120       14        19217           8,66         3
3            5        120       12        64864           8,43         4
4            6        480       14        13468           8,70         5

  Complexity Average  Owned Users  \
0               3,86      68323.0
1               2,84      65294.0
2               3,91      28785.0
3               3,24      87099.0
4               4,22      16831.0

                                           Mechanics  \
0  Action Queue, Action Retrieval, Campaign / Bat...
1  Action Points, Cooperative Game, Hand Manageme...
2  Hand Management, Income, Loans, Market, Networ...
3  Card Drafting, Drafting, End Game Bonuses, Han...
4  Action Drafting, Area Majority / Influence, Ar...

                          Domains
0  Strategy Games, Thematic Games
1  Strategy Games, Thematic Games
2                  Strategy Games
3                  Strategy Games
4  Strategy Games, Thematic Games

In [4]:
df['Complexity Average'] = df['Complexity Average'].str.replace(',', '.').astype(float)
df.head()

,ID,Name,Year Published,Min Players,Max Players,Play Time,Min Age,Users Rated,Rating Average,BGG Rank,Complexity Average,Owned Users,Mechanics,Domains
0,174430,Gloomhaven,2017.0,1,4,120,14,42055,"8,79",1,3.86,68323.0,"Action Queue, Action Retrieval, Campaign / Bat...","Strategy Games, Thematic Games"
1,161936,Pandemic Legacy: Season 1,2015.0,2,4,60,13,41643,"8,61",2,2.84,65294.0,"Action Points, Cooperative Game, Hand Manageme...","Strategy Games, Thematic Games"
2,224517,Brass: Birmingham,2018.0,2,4,120,14,19217,"8,66",3,3.91,28785.0,"Hand Management, Income, Loans, Market, Networ...",Strategy Games
3,167791,Terraforming Mars,2016.0,1,5,120,12,64864,"8,43",4,3.24,87099.0,"Card Drafting, Drafting, End Game Bonuses, Han...",Strategy Games
4,233078,Twilight Imperium: Fourth Edition,2017.0,3,6,480,14,13468,"8,70",5,4.22,16831.0,"Action Drafting, Area Majority / Influence, Ar...","Strategy Games, Thematic Games"

In [5]:
df['Rating Average'] = df['Rating Average'].str.replace(',', '.').astype(float)
df.head()

,ID,Name,Year Published,Min Players,Max Players,Play Time,Min Age,Users Rated,Rating Average,BGG Rank,Complexity Average,Owned Users,Mechanics,Domains
0,174430,Gloomhaven,2017.0,1,4,120,14,42055,8.79,1,3.86,68323.0,"Action Queue, Action Retrieval, Campaign / Bat...","Strategy Games, Thematic Games"
1,161936,Pandemic Legacy: Season 1,2015.0,2,4,60,13,41643,8.61,2,2.84,65294.0,"Action Points, Cooperative Game, Hand Manageme...","Strategy Games, Thematic Games"
2,224517,Brass: Birmingham,2018.0,2,4,120,14,19217,8.66,3,3.91,28785.0,"Hand Management, Income, Loans, Market, Networ...",Strategy Games
3,167791,Terraforming Mars,2016.0,1,5,120,12,64864,8.43,4,3.24,87099.0,"Card Drafting, Drafting, End Game Bonuses, Han...",Strategy Games
4,233078,Twilight Imperium: Fourth Edition,2017.0,3,6,480,14,13468,8.70,5,4.22,16831.0,"Action Drafting, Area Majority / Influence, Ar...","Strategy Games, Thematic Games"

In [6]:
# Assuming 'df' has a column 'Domains' that you want to split
df_split = df['Domains'].str.split(',', expand=True)

# Add the split columns back to the original DataFrame
df[['Domain1', 'Domain2', 'Domain3']] = df_split

# Display the updated DataFrame
print(df.head())

       ID                               Name  Year Published  Min Players  \
0  174430                         Gloomhaven          2017.0            1
1  161936          Pandemic Legacy: Season 1          2015.0            2
2  224517                  Brass: Birmingham          2018.0            2
3  167791                  Terraforming Mars          2016.0            1
4  233078  Twilight Imperium: Fourth Edition          2017.0            3

   Max Players  Play Time  Min Age  Users Rated  Rating Average  BGG Rank  \
0            4        120       14        42055            8.79         1
1            4         60       13        41643            8.61         2
2            4        120       14        19217            8.66         3
3            5        120       12        64864            8.43         4
4            6        480       14        13468            8.70         5

   Complexity Average  Owned Users  \
0                3.86      68323.0
1                2.84      65294.0
2                3.91      28785.0
3                3.24      87099.0
4                4.22      16831.0

                                           Mechanics  \
0  Action Queue, Action Retrieval, Campaign / Bat...
1  Action Points, Cooperative Game, Hand Manageme...
2  Hand Management, Income, Loans, Market, Networ...
3  Card Drafting, Drafting, End Game Bonuses, Han...
4  Action Drafting, Area Majority / Influence, Ar...

                          Domains         Domain1          Domain2 Domain3
0  Strategy Games, Thematic Games  Strategy Games   Thematic Games    None
1  Strategy Games, Thematic Games  Strategy Games   Thematic Games    None
2                  Strategy Games  Strategy Games             None    None
3                  Strategy Games  Strategy Games             None    None
4  Strategy Games, Thematic Games  Strategy Games   Thematic Games    None

In [7]:
df = df.drop(columns=['Domains', 'Mechanics'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20343 entries, 0 to 20342
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  20343 non-null  int32
 1   Name                20343 non-null  object
 2   Year Published      20342 non-null  float64
 3   Min Players         20343 non-null  int64
 4   Max Players         20343 non-null  int64
 5   Play Time           20343 non-null  int64
 6   Min Age             20343 non-null  int64
 7   Users Rated         20343 non-null  int64
 8   Rating Average      20343 non-null  float64
 9   BGG Rank            20343 non-null  int64
 10  Complexity Average  20343 non-null  float64
 11  Owned Users         20320 non-null  float64
 12  Domain1             10184 non-null  object
 13  Domain2             1492 non-null   object
 14  Domain3             13 non-null     object
dtypes: float64(4), int32(1), int64(6), object(4)
memory usage: 2.3+ MB

In [7]:
#import pandas as pd

# Assuming 'df' is your DataFrame and has a column 'Mechanics' that you want to split
#df_split = df['Mechanics'].str.split(',', expand=True)

# Display the first few rows to confirm the split
#print(df_split.head())

In [8]:
# Add the first 7 split columns back to the original DataFrame with appropriate column names
#df[['Mechanic1', 'Mechanic2', 'Mechanic3', 'Mechanic4', 'Mechanic5', 'Mechanic6', 'Mechanic7']] = df_split.iloc[:, :7]

# Display the updated DataFrame to confirm the addition
#print(df.head())

In [9]:
# Drop the unnecessary columns (8th to 19th columns from the split)
# Note: The indexes in df_split start from 0, so columns 7 to 18 are the ones to drop
#df_split = df_split.drop(df_split.columns[7:], axis=1)

# Display the split DataFrame to confirm the columns have been dropped
#print(df_split.head())

In [10]:
# If you want to drop the original 'Mechanics' column from the DataFrame
#df = df.drop(columns=['Mechanics'])

# Display the final DataFrame to confirm the changes
#print(df.head())

In [8]:
# Calculate the range (min and max)
min_value = df['Rating Average'].min()
max_value = df['Rating Average'].max()
value_range = max_value - min_value

# Calculate the median
median_value = df['Rating Average'].median()

# Display the results
print(f"Minimum Value: {min_value}")
print(f"Maximum Value: {max_value}")
print(f"Range: {value_range}")
print(f"Median Value: {median_value}")

Minimum Value: 1.05
Maximum Value: 9.58
Range: 8.53
Median Value: 6.43

In [9]:
df['above_average'] = df['Rating Average'] > 6.43
df.head()

,ID,Name,Year Published,Min Players,Max Players,Play Time,Min Age,Users Rated,Rating Average,BGG Rank,Complexity Average,Owned Users,Domain1,Domain2,Domain3,above_average
0,174430,Gloomhaven,2017.0,1,4,120,14,42055,8.79,1,3.86,68323.0,Strategy Games,Thematic Games,None,True
1,161936,Pandemic Legacy: Season 1,2015.0,2,4,60,13,41643,8.61,2,2.84,65294.0,Strategy Games,Thematic Games,None,True
2,224517,Brass: Birmingham,2018.0,2,4,120,14,19217,8.66,3,3.91,28785.0,Strategy Games,None,None,True
3,167791,Terraforming Mars,2016.0,1,5,120,12,64864,8.43,4,3.24,87099.0,Strategy Games,None,None,True
4,233078,Twilight Imperium: Fourth Edition,2017.0,3,6,480,14,13468,8.70,5,4.22,16831.0,Strategy Games,Thematic Games,None,True

In [13]:
"""
# Reset rows 401 to 600 to their original state, if you know what they were
df.loc[8000:, ['Bayesian Average', 'Most Notable Genre', 'Most Notable Mechanic', 'Price']] = None
"""

"\n# Reset rows 401 to 600 to their original state, if you know what they were\ndf.loc[8000:, ['Bayesian Average', 'Most Notable Genre', 'Most Notable Mechanic', 'Price']] = None\n"

In [14]:
"""
# Select and display the specific columns in rows 421 to 440
print(df.loc[16620:16629, ['Bayesian Average', 'Most Notable Genre', 'Most Notable Mechanic', 'Price']])
"""

"\n# Select and display the specific columns in rows 421 to 440\nprint(df.loc[16620:16629, ['Bayesian Average', 'Most Notable Genre', 'Most Notable Mechanic', 'Price']])\n"

In [15]:
"""
import requests
import xml.etree.ElementTree as ET
import pandas as pd

# Function to fetch details from BoardGameGeek API with added error handling
def fetch_game_details(game_id):
    game_id_str = str(int(game_id))
    game_url = f"https://boardgamegeek.com/xmlapi/boardgame/{game_id_str}?stats=1&pricehistory=1"
    game_response = requests.get(game_url)
    
    # Debug: Print the game ID and response status code
    print(f"Fetching details for Game ID: {game_id_str} (Status Code: {game_response.status_code})")
    
    if game_response.status_code == 200:
        try:
            game_root = ET.fromstring(game_response.content)
        except ET.ParseError as e:
            # Handle the XML parsing error
            print(f"XML parsing error for Game ID {game_id_str}: {e}")
            print("Response content:", game_response.content.decode('utf-8'))
            return "Parsing Error", "Parsing Error", "Parsing Error", "Parsing Error"
        
        bayesaverage_element = game_root.find('.//statistics/ratings/bayesaverage')
        bayesaverage = bayesaverage_element.text if bayesaverage_element is not None else "Not available"
        
        genre_element = game_root.find('.//boardgamecategory')
        genre = genre_element.text if genre_element is not None else "Not available"
        
        mechanic_element = game_root.find('.//boardgamemechanic')
        mechanic = mechanic_element.text if mechanic_element is not None else "Not available"
        
        price_element = game_root.find('.//marketplacehistory/listing/price')
        price = price_element.text if price_element is not None else "Not available"
        
        # Debug: Print the fetched data
        print(f"Bayes Average: {bayesaverage}, Genre: {genre}, Mechanic: {mechanic}, Price: {price}")
        
        return bayesaverage, genre, mechanic, price
    
    print("Failed to fetch data or game not found.")
    return "Not available", "Not available", "Not available", "Not available"

# Initialize empty lists to hold the new data
bayesaverages = []
genres = []
mechanics = []
prices = []

# Run the code on rows 1001 to 1400 of the DataFrame
for index, row in df.iloc[8000:].iterrows():  # df.iloc[1000:1400] selects rows 1001 to 1400
    game_id = row['ID']  # Ensure 'ID' is the correct column name
    
    # Check if 'Bayesian Average' is already populated for the row
    if pd.isna(row.get('Bayesian Average')) and game_id != 0:  # Skip if already populated or ID is 0
        bayesaverage, genre, mechanic, price = fetch_game_details(game_id)
    else:
        bayesaverage, genre, mechanic, price = row.get('Bayesian Average'), row.get('Most Notable Genre'), row.get('Most Notable Mechanic'), row.get('Price')
    
    # Append the results to the lists
    bayesaverages.append(bayesaverage)
    genres.append(genre)
    mechanics.append(mechanic)
    prices.append(price)

# Update the DataFrame with new data, only affecting rows 1001 to 1400 (indices 1000 to 1399)
df.loc[8000:, 'Bayesian Average'] = bayesaverages
df.loc[8000:, 'Most Notable Genre'] = genres
df.loc[8000:, 'Most Notable Mechanic'] = mechanics
df.loc[8000:, 'Price'] = prices

# Display the updated DataFrame for rows 1391 to 1400
print(df.iloc[20010:20020])
"""

'\nimport requests\nimport xml.etree.ElementTree as ET\nimport pandas as pd\n\n# Function to fetch details from BoardGameGeek API with added error handling\ndef fetch_game_details(game_id):\n    game_id_str = str(int(game_id))\n    game_url = f"https://boardgamegeek.com/xmlapi/boardgame/{game_id_str}?stats=1&pricehistory=1"\n    game_response = requests.get(game_url)\n    \n    # Debug: Print the game ID and response status code\n    print(f"Fetching details for Game ID: {game_id_str} (Status Code: {game_response.status_code})")\n    \n    if game_response.status_code == 200:\n        try:\n            game_root = ET.fromstring(game_response.content)\n        except ET.ParseError as e:\n            # Handle the XML parsing error\n            print(f"XML parsing error for Game ID {game_id_str}: {e}")\n            print("Response content:", game_response.content.decode(\'utf-8\'))\n            return "Parsing Error", "Parsing Error", "Parsing Error", "Parsing Error"\n        \n        bayesaverage_element = game_root.find(\'.//statistics/ratings/bayesaverage\')\n        bayesaverage = bayesaverage_element.text if bayesaverage_element is not None else "Not available"\n        \n        genre_element = game_root.find(\'.//boardgamecategory\')\n        genre = genre_element.text if genre_element is not None else "Not available"\n        \n        mechanic_element = game_root.find(\'.//boardgamemechanic\')\n        mechanic = mechanic_element.text if mechanic_element is not None else "Not available"\n        \n        price_element = game_root.find(\'.//marketplacehistory/listing/price\')\n        price = price_element.text if price_element is not None else "Not available"\n        \n        # Debug: Print the fetched data\n        print(f"Bayes Average: {bayesaverage}, Genre: {genre}, Mechanic: {mechanic}, Price: {price}")\n        \n        return bayesaverage, genre, mechanic, price\n    \n    print("Failed to fetch data or game not found.")\n    return "Not available", "Not available", "Not available", "Not available"\n\n# Initialize empty lists to hold the new data\nbayesaverages = []\ngenres = []\nmechanics = []\nprices = []\n\n# Run the code on rows 1001 to 1400 of the DataFrame\nfor index, row in df.iloc[8000:].iterrows():  # df.iloc[1000:1400] selects rows 1001 to 1400\n    game_id = row[\'ID\']  # Ensure \'ID\' is the correct column name\n    \n    # Check if \'Bayesian Average\' is already populated for the row\n    if pd.isna(row.get(\'Bayesian Average\')) and game_id != 0:  # Skip if already populated or ID is 0\n        bayesaverage, genre, mechanic, price = fetch_game_details(game_id)\n    else:\n        bayesaverage, genre, mechanic, price = row.get(\'Bayesian Average\'), row.get(\'Most Notable Genre\'), row.get(\'Most Notable Mechanic\'), row.get(\'Price\')\n    \n    # Append the results to the lists\n    bayesaverages.append(bayesaverage)\n    genres.append(genre)\n    mechanics.append(mechanic)\n    prices.append(price)\n\n# Update the DataFrame with new data, only affecting rows 1001 to 1400 (indices 1000 to 1399)\ndf.loc[8000:, \'Bayesian Average\'] = bayesaverages\ndf.loc[8000:, \'Most Notable Genre\'] = genres\ndf.loc[8000:, \'Most Notable Mechanic\'] = mechanics\ndf.loc[8000:, \'Price\'] = prices\n\n# Display the updated DataFrame for rows 1391 to 1400\nprint(df.iloc[20010:20020])\n'

In [10]:
import pandas as pd

# Adjust the delimiter based on your file's structure
price_df = pd.read_csv('./Resources/board_game_price.csv', delimiter=',')

# Display the first few rows
print(price_df.head())

                                Name  Min Players  Max Players  Play Time  \
0                         Gloomhaven            1            4        120
1          Pandemic Legacy: Season 1            2            4         60
2                  Brass: Birmingham            2            4        120
3                  Terraforming Mars            1            5        120
4  Twilight Imperium: Fourth Edition            3            6        480

   Min Age  Users Rated  Rating Average  Complexity Average  Owned Users  \
0       14        42055            8.79                3.86      68323.0
1       13        41643            8.61                2.84      65294.0
2       14        19217            8.66                3.91      28785.0
3       12        64864            8.43                3.24      87099.0
4       14        13468            8.70                4.22      16831.0

          Domain1  above_average Bayesian Average Most Notable Genre  \
0  Strategy Games           True          8.34764          Adventure
1  Strategy Games           True          8.37666      Environmental
2  Strategy Games           True          8.41236      Age of Reason
3  Strategy Games           True          8.20958           Economic
4  Strategy Games           True           8.2379       Civilization

  Most Notable Mechanic   Price
0          Action Queue      99
1         Action Points    49.5
2       Hand Management     105
3       Closed Drafting    69.9
4       Action Drafting  127.99

In [11]:
# Calculate the percentage of users rated and round to 2 decimal places
price_df['pct_rated'] = round(price_df['Users Rated'] / price_df['Owned Users'], 2)

price_df['pct_rated'].replace([float('inf'), float('-inf')], 0, inplace=True)

# Display the first few rows of the DataFrame
print(price_df.head())

                                Name  Min Players  Max Players  Play Time  \
0                         Gloomhaven            1            4        120
1          Pandemic Legacy: Season 1            2            4         60
2                  Brass: Birmingham            2            4        120
3                  Terraforming Mars            1            5        120
4  Twilight Imperium: Fourth Edition            3            6        480

   Min Age  Users Rated  Rating Average  Complexity Average  Owned Users  \
0       14        42055            8.79                3.86      68323.0
1       13        41643            8.61                2.84      65294.0
2       14        19217            8.66                3.91      28785.0
3       12        64864            8.43                3.24      87099.0
4       14        13468            8.70                4.22      16831.0

          Domain1  above_average Bayesian Average Most Notable Genre  \
0  Strategy Games           True          8.34764          Adventure
1  Strategy Games           True          8.37666      Environmental
2  Strategy Games           True          8.41236      Age of Reason
3  Strategy Games           True          8.20958           Economic
4  Strategy Games           True           8.2379       Civilization

  Most Notable Mechanic   Price  pct_rated
0          Action Queue      99       0.62
1         Action Points    49.5       0.64
2       Hand Management     105       0.67
3       Closed Drafting    69.9       0.74
4       Action Drafting  127.99       0.80

In [12]:
price_df['Domain1'] = price_df['Domain1'].fillna('other')

In [13]:
# Replace NaN values with 0 in the 'Bayesian Average' column
price_df['Bayesian Average'].fillna(0, inplace=True)

# Verify the replacement by checking if there are any remaining NaNs
null_count_after = price_df['Bayesian Average'].isna().sum()

print(f'Number of null values after replacement: {null_count_after}')

Number of null values after replacement: 0

In [14]:
# Strip any leading/trailing spaces or hidden characters
price_df['Bayesian Average'] = price_df['Bayesian Average'].str.strip()

# Replace any remaining non-numeric values with NaN, then fill NaNs with 0
price_df['Bayesian Average'] = pd.to_numeric(price_df['Bayesian Average'], errors='coerce').fillna(0)

# Round the values to 2 decimal places
price_df['Bayesian Average'] = price_df['Bayesian Average'].round(2)

# Verify the conversion
print(price_df['Bayesian Average'].dtype)

float64

In [15]:
# Round the values in the 'Bayesian Average' column to 2 decimal places
price_df['Bayesian Average'] = price_df['Bayesian Average'].round(2)

In [16]:
# Calculate the range (min and max)
min_value = price_df['Bayesian Average'][price_df['Bayesian Average'] > 0].min()
max_value = price_df['Bayesian Average'].max()
value_range = max_value - min_value

# Calculate the median
median_value = price_df['Bayesian Average'].median()

# Display the results
print(f"Minimum Value: {min_value}")
print(f"Maximum Value: {max_value}")
print(f"Range: {value_range}")
print(f"Median Value: {median_value}")

Minimum Value: 3.65
Maximum Value: 8.41
Range: 4.76
Median Value: 5.54

In [17]:
price_df['bayes_above_average'] = price_df['Bayesian Average'] > 5.54
price_df.head()

,Name,Min Players,Max Players,Play Time,Min Age,Users Rated,Rating Average,Complexity Average,Owned Users,Domain1,above_average,Bayesian Average,Most Notable Genre,Most Notable Mechanic,Price,pct_rated,bayes_above_average
0,Gloomhaven,1,4,120,14,42055,8.79,3.86,68323.0,Strategy Games,True,8.35,Adventure,Action Queue,99,0.62,True
1,Pandemic Legacy: Season 1,2,4,60,13,41643,8.61,2.84,65294.0,Strategy Games,True,8.38,Environmental,Action Points,49.5,0.64,True
2,Brass: Birmingham,2,4,120,14,19217,8.66,3.91,28785.0,Strategy Games,True,8.41,Age of Reason,Hand Management,105,0.67,True
3,Terraforming Mars,1,5,120,12,64864,8.43,3.24,87099.0,Strategy Games,True,8.21,Economic,Closed Drafting,69.9,0.74,True
4,Twilight Imperium: Fourth Edition,3,6,480,14,13468,8.70,4.22,16831.0,Strategy Games,True,8.24,Civilization,Action Drafting,127.99,0.80,True

In [18]:
price_df['Owned Users'].fillna(0, inplace=True)
# Calculate the mean of the non-zero 'Price' values
non_zero_mean = price_df[price_df['Owned Users'] > 0]['Owned Users'].mean()

# Print the calculated mean
print(f'The mean of non-zero Owners is: {non_zero_mean}')

price_df.loc[price_df['Owned Users'] == 0, 'Owned Users'] = non_zero_mean

The mean of non-zero Owners is: 1408.5269452236823

In [19]:
price_df[['Most Notable Genre', 'Most Notable Mechanic']] = price_df[['Most Notable Genre', 'Most Notable Mechanic']].fillna('unspecified')

In [20]:
# Replace NaN values with 0 in the 'Bayesian Average' column
price_df['Price'].fillna(0, inplace=True)

# Verify the replacement by checking if there are any remaining NaNs
null_count_after = price_df['Price'].isna().sum()

print(f'Number of null values after replacement: {null_count_after}')

Number of null values after replacement: 0

In [21]:
# Strip any leading/trailing spaces or hidden characters
price_df['Price'] = price_df['Price'].str.strip()

# Replace any remaining non-numeric values with NaN, then fill NaNs with 0
price_df['Price'] = pd.to_numeric(price_df['Price'], errors='coerce').fillna(0)

# Round the values to 2 decimal places
price_df['Price'] = price_df['Price'].round(2)

# Verify the conversion
print(price_df['Price'].dtype)

price_df['Price'] = price_df['Price'].round(2)

float64

In [22]:
# Calculate the range (min and max)
min_value = price_df['Price'][price_df['Price'] > 0].min()
max_value = price_df['Price'].max()
value_range = max_value - min_value

# Calculate the median
median_value = price_df['Price'].median()

# Display the results
print(f"Minimum Value: {min_value}")
print(f"Maximum Value: {max_value}")
print(f"Range: {value_range}")
print(f"Median Value: {median_value}")

Minimum Value: 0.01
Maximum Value: 1700.0
Range: 1699.99
Median Value: 15.49

In [23]:
price_df['Price'] = price_df['Price'].apply(lambda x: 15.50 if x == 0 else x)

In [24]:
price_df['pct_rated'] = round(price_df['Users Rated'] / price_df['Owned Users'], 2)

In [25]:
null_counts = price_df.isnull().sum()
print(null_counts)

Name                     0
Min Players              0
Max Players              0
Play Time                0
Min Age                  0
Users Rated              0
Rating Average           0
Complexity Average       0
Owned Users              0
Domain1                  0
above_average            0
Bayesian Average         0
Most Notable Genre       0
Most Notable Mechanic    0
Price                    0
pct_rated                0
bayes_above_average      0
dtype: int64

In [26]:
import pandas as pd

# Adjust the delimiter based on your file's structure
df = pd.read_csv('./Resources/latest_bg.csv', delimiter=',')

# Display the first few rows
print(df.head())

                                Name  Min Players  Max Players  Play Time  \
0                         Gloomhaven            1            4        120
1          Pandemic Legacy: Season 1            2            4         60
2                  Brass: Birmingham            2            4        120
3                  Terraforming Mars            1            5        120
4  Twilight Imperium: Fourth Edition            3            6        480

   Min Age  Users Rated  Rating Average  Complexity Average  Owned Users  \
0       14        42055            8.79                3.86      68323.0
1       13        41643            8.61                2.84      65294.0
2       14        19217            8.66                3.91      28785.0
3       12        64864            8.43                3.24      87099.0
4       14        13468            8.70                4.22      16831.0

          Domain1  above_average  Bayesian Average Most Notable Genre  \
0  Strategy Games           True              8.35          Adventure
1  Strategy Games           True              8.38      Environmental
2  Strategy Games           True              8.41      Age of Reason
3  Strategy Games           True              8.21           Economic
4  Strategy Games           True              8.24       Civilization

  Most Notable Mechanic   Price  pct_rated  bayes_above_average
0          Action Queue   99.00       0.62                 True
1         Action Points   49.50       0.64                 True
2       Hand Management  105.00       0.67                 True
3       Closed Drafting   69.90       0.74                 True
4       Action Drafting  127.99       0.80                 True

In [27]:
import pandas as pd

# Adjust the delimiter based on your file's structure
df2 = pd.read_csv('./Resources/bgg_dataset.csv', delimiter=';')

# Display the first few rows
print(df2.head())

         ID                               Name  Year Published  Min Players  \
0  174430.0                         Gloomhaven          2017.0            1
1  161936.0          Pandemic Legacy: Season 1          2015.0            2
2  224517.0                  Brass: Birmingham          2018.0            2
3  167791.0                  Terraforming Mars          2016.0            1
4  233078.0  Twilight Imperium: Fourth Edition          2017.0            3

   Max Players  Play Time  Min Age  Users Rated Rating Average  BGG Rank  \
0            4        120       14        42055           8,79         1
1            4         60       13        41643           8,61         2
2            4        120       14        19217           8,66         3
3            5        120       12        64864           8,43         4
4            6        480       14        13468           8,70         5

  Complexity Average  Owned Users  \
0               3,86      68323.0
1               2,84      65294.0
2               3,91      28785.0
3               3,24      87099.0
4               4,22      16831.0

                                           Mechanics  \
0  Action Queue, Action Retrieval, Campaign / Bat...
1  Action Points, Cooperative Game, Hand Manageme...
2  Hand Management, Income, Loans, Market, Networ...
3  Card Drafting, Drafting, End Game Bonuses, Han...
4  Action Drafting, Area Majority / Influence, Ar...

                          Domains
0  Strategy Games, Thematic Games
1  Strategy Games, Thematic Games
2                  Strategy Games
3                  Strategy Games
4  Strategy Games, Thematic Games

In [28]:
import pandas as pd

# Perform the merge
df_merged = pd.merge(df, df2[['Name', 'Year Published']], 
                     on='Name', 
                     how='left')

df_merged.head()

,Name,Min Players,Max Players,Play Time,Min Age,Users Rated,Rating Average,Complexity Average,Owned Users,Domain1,above_average,Bayesian Average,Most Notable Genre,Most Notable Mechanic,Price,pct_rated,bayes_above_average,Year Published
0,Gloomhaven,1,4,120,14,42055,8.79,3.86,68323.0,Strategy Games,True,8.35,Adventure,Action Queue,99.00,0.62,True,2017.0
1,Pandemic Legacy: Season 1,2,4,60,13,41643,8.61,2.84,65294.0,Strategy Games,True,8.38,Environmental,Action Points,49.50,0.64,True,2015.0
2,Brass: Birmingham,2,4,120,14,19217,8.66,3.91,28785.0,Strategy Games,True,8.41,Age of Reason,Hand Management,105.00,0.67,True,2018.0
3,Terraforming Mars,1,5,120,12,64864,8.43,3.24,87099.0,Strategy Games,True,8.21,Economic,Closed Drafting,69.90,0.74,True,2016.0
4,Twilight Imperium: Fourth Edition,3,6,480,14,13468,8.70,4.22,16831.0,Strategy Games,True,8.24,Civilization,Action Drafting,127.99,0.80,True,2017.0

In [29]:
null_counts = df_merged.isnull().sum()
print(null_counts)

Name                     0
Min Players              0
Max Players              0
Play Time                0
Min Age                  0
Users Rated              0
Rating Average           0
Complexity Average       0
Owned Users              0
Domain1                  0
above_average            0
Bayesian Average         0
Most Notable Genre       0
Most Notable Mechanic    0
Price                    0
pct_rated                0
bayes_above_average      0
Year Published           1
dtype: int64

In [30]:
df_merged = df_merged.dropna()

In [31]:
# Round the 'Owned Users' column to 0 decimal places and convert it to integers
df_merged['Owned Users'] = df_merged['Owned Users'].round(0).astype(int)
df_merged['Year Published'] = df_merged['Year Published'].round(0).astype(int)

In [32]:
# Calculate the range (min and max)
min_value = df_merged['Owned Users'][df_merged['Owned Users'] > 0].min()
max_value = df_merged['Owned Users'].max()
value_range = max_value - min_value

# Calculate the median
median_value = df_merged['Owned Users'].median()

# Display the results
print(f"Minimum Value: {min_value}")
print(f"Maximum Value: {max_value}")
print(f"Range: {value_range}")
print(f"Median Value: {median_value}")

Minimum Value: 3
Maximum Value: 155312
Range: 155309
Median Value: 311.0

In [33]:
df_merged['Owned_Bool'] = df_merged['Owned Users'] > 311
df_merged.head()

,Name,Min Players,Max Players,Play Time,Min Age,Users Rated,Rating Average,Complexity Average,Owned Users,Domain1,above_average,Bayesian Average,Most Notable Genre,Most Notable Mechanic,Price,pct_rated,bayes_above_average,Year Published,Owned_Bool
0,Gloomhaven,1,4,120,14,42055,8.79,3.86,68323,Strategy Games,True,8.35,Adventure,Action Queue,99.00,0.62,True,2017,True
1,Pandemic Legacy: Season 1,2,4,60,13,41643,8.61,2.84,65294,Strategy Games,True,8.38,Environmental,Action Points,49.50,0.64,True,2015,True
2,Brass: Birmingham,2,4,120,14,19217,8.66,3.91,28785,Strategy Games,True,8.41,Age of Reason,Hand Management,105.00,0.67,True,2018,True
3,Terraforming Mars,1,5,120,12,64864,8.43,3.24,87099,Strategy Games,True,8.21,Economic,Closed Drafting,69.90,0.74,True,2016,True
4,Twilight Imperium: Fourth Edition,3,6,480,14,13468,8.70,4.22,16831,Strategy Games,True,8.24,Civilization,Action Drafting,127.99,0.80,True,2017,True

In [34]:
df_merged['Owned_Bool'].value_counts()

Owned_Bool
False    10614
True     10572
Name: count, dtype: int64

In [35]:
df_merged['Year Offset'] = 2024 - df_merged['Year Published']

In [36]:
df_merged['Owned_Per_Year'] = round((df_merged['Owned Users'] / df_merged['Year Offset']),2)

In [37]:
# Calculate the range (min and max)
min_value = df_merged['Owned_Per_Year'][df_merged['Owned_Per_Year'] > 0].min()
max_value = df_merged['Owned_Per_Year'].max()
value_range = max_value - min_value

# Calculate the median
median_value = df_merged['Owned_Per_Year'].median()

# Display the results
print(f"Minimum Value: {min_value}")
print(f"Maximum Value: {max_value}")
print(f"Range: {value_range}")
print(f"Median Value: {median_value}")

Minimum Value: 0.01
Maximum Value: 18579.2
Range: 18579.190000000002
Median Value: 23.33

In [38]:
df_merged['perYear_Bool'] = df_merged['Owned_Per_Year'] > 23.33
df_merged.head()

,Name,Min Players,Max Players,Play Time,Min Age,Users Rated,Rating Average,Complexity Average,Owned Users,Domain1,...,Most Notable Genre,Most Notable Mechanic,Price,pct_rated,bayes_above_average,Year Published,Owned_Bool,Year Offset,Owned_Per_Year,perYear_Bool
0,Gloomhaven,1,4,120,14,42055,8.79,3.86,68323,Strategy Games,...,Adventure,Action Queue,99.00,0.62,True,2017,True,7,9760.43,True
1,Pandemic Legacy: Season 1,2,4,60,13,41643,8.61,2.84,65294,Strategy Games,...,Environmental,Action Points,49.50,0.64,True,2015,True,9,7254.89,True
2,Brass: Birmingham,2,4,120,14,19217,8.66,3.91,28785,Strategy Games,...,Age of Reason,Hand Management,105.00,0.67,True,2018,True,6,4797.50,True
3,Terraforming Mars,1,5,120,12,64864,8.43,3.24,87099,Strategy Games,...,Economic,Closed Drafting,69.90,0.74,True,2016,True,8,10887.38,True
4,Twilight Imperium: Fourth Edition,3,6,480,14,13468,8.70,4.22,16831,Strategy Games,...,Civilization,Action Drafting,127.99,0.80,True,2017,True,7,2404.43,True

In [39]:
df_merged.to_csv('./Resources/model_dataset.csv', index=False)